"""
Django settings for UNIS_back project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Базовый путь проекта (корневая директория)
BASE_DIR = Path(__file__).resolve().parent.parent


# Настройки быстрого старта - не подходят для продакшена
# См. https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# ВНИМАНИЕ: секретный ключ должен храниться в безопасности в продакшене!
SECRET_KEY = 'django-insecure-=@gj0bnk=@cn3h$=uzjyhwvba!$09z432=rns1swr3fc72z^kf'

# ВНИМАНИЕ: режим отладки должен быть выключен в продакшене!
DEBUG = True

ALLOWED_HOSTS = []


# Установленные приложения

INSTALLED_APPS = [
    'django.contrib.admin',  # Административная панель Django
    'django.contrib.auth',   # Система аутентификации и пользователей
    'django.contrib.contenttypes',  # Система типов содержимого
    'django.contrib.sessions',  # Сессии для хранения данных
    'django.contrib.messages',  # Система сообщений
    'django.contrib.staticfiles',  # Управление статическими файлами
    'corsheaders',  # Поддержка CORS для API
    'rest_framework',  # Django REST Framework для API
    'rest_framework.authtoken',  # Аутентификация на основе токенов
    'main',  # Основное приложение проекта
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Безопасность
    'django.contrib.sessions.middleware.SessionMiddleware',  # Сессии
    'corsheaders.middleware.CorsMiddleware',  # CORS - должен быть перед CommonMiddleware
    'django.middleware.common.CommonMiddleware',  # Общие функции
    'django.middleware.csrf.CsrfViewMiddleware',  # Защита от CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Аутентификация
    'django.contrib.messages.middleware.MessageMiddleware',  # Сообщения
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Защита от кликджекинга
]

# Настройка CORS для разработки - разрешить все источники
# В продакшене следует указать конкретные разрешенные источники
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:4200",
#     "http://localhost:63697",
# ]

# Разрешить запросы с любого источника (только для разработки!)
CORS_ALLOW_ALL_ORIGINS = True

# Настройки Rest Framework для аутентификации
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Аутентификация по токенам
    ],
}

ROOT_URLCONF = 'UNIS_back.urls'  # Основной файл URL маршрутов

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UNIS_back.wsgi.application'  # Точка входа для WSGI серверов


# База данных
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite - простая БД для разработки
        'NAME': BASE_DIR / 'db.sqlite3',  # Путь к файлу БД
    }
}


# Валидация паролей
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Проверка на схожесть с атрибутами пользователя
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Минимальная длина
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Проверка на популярные пароли
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Проверка на полностью числовые пароли
    },
]


# Интернационализация
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Язык по умолчанию

TIME_ZONE = 'UTC'  # Временная зона

USE_I18N = True  # Включить интернационализацию

USE_TZ = True  # Использовать временные зоны


# Статические файлы (CSS, JavaScript, изображения)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'  # URL путь к статическим файлам

# Тип первичного ключа по умолчанию
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Тип автоинкрементного поля для новых моделей
